const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcrypt');

const prisma = new PrismaClient();

async function main() {
  const hashedPassword = await bcrypt.hash("12345678", 10);

  const recruitersData = [
    {
      user: {
        email: "john.doe@deere.com",
        name: "John Doe",
        image: "https://via.placeholder.com/150/0000FF/FFFFFF?text=JD",
        phone: "+1-309-765-4321",
        location: "Moline, Illinois, USA",
        bio: "Experienced recruiter in agriculture technology.",
        skills: ["Recruitment", "Agriculture", "HR"],
        experience: "10+ years in HR",
        education: "MBA from University of Illinois",
      },
      company: {
        name: "John Deere",
        slug: "john-deere",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/John-Deere-Logo.png",
        description: "John Deere is a world leader in agricultural machinery and technology.",
        industry: "Agriculture",
        size: "5000+",
        location: "Moline, Illinois, USA",
        website: "https://www.deere.com",
        founded: "1837",
      },
      jobs: [
        {
          title: "Agricultural Engineer",
          slug: "agricultural-engineer-john-deere",
          description: "Design and develop agricultural machinery and equipment.",
          requirements: ["Bachelor's in Agricultural Engineering", "5+ years experience", "CAD proficiency"],
          responsibilities: ["Design machinery", "Test prototypes", "Collaborate with teams"],
          benefits: ["Health insurance", "Retirement plan", "Paid time off"],
          skills: ["Engineering", "CAD", "Agriculture"],
          type: "FULL_TIME",
          experience: "5-10 years",
          salary: "$80,000 - $120,000",
          location: "Moline, Illinois, USA",
          isRemote: false,
          deadline: new Date("2025-12-31"),
          category: "Engineering",
        },
        {
          title: "HR Specialist",
          slug: "hr-specialist-john-deere",
          description: "Manage recruitment and employee relations in agriculture sector.",
          requirements: ["Bachelor's in HR", "3+ years experience", "Communication skills"],
          responsibilities: ["Recruit talent", "Handle employee issues", "Develop policies"],
          benefits: ["Health insurance", "Retirement plan", "Paid time off"],
          skills: ["HR", "Recruitment", "Communication"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "$60,000 - $90,000",
          location: "Moline, Illinois, USA",
          isRemote: false,
          deadline: new Date("2025-11-30"),
          category: "HR",
        },
      ],
    },
    {
      user: {
        email: "jane.smith@jpmorganchase.com",
        name: "Jane Smith",
        image: "https://via.placeholder.com/150/FF0000/FFFFFF?text=JS",
        phone: "+1-212-555-1234",
        location: "New York, NY, USA",
        bio: "Banking recruitment expert with focus on finance roles.",
        skills: ["Banking", "Finance", "Recruitment"],
        experience: "12+ years in finance HR",
        education: "MBA from Columbia University",
      },
      company: {
        name: "JPMorgan Chase",
        slug: "jpmorgan-chase",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/JPMorgan-Chase-Logo.png",
        description: "JPMorgan Chase is a leading global financial services firm.",
        industry: "Banking & Finance",
        size: "5000+",
        location: "New York, NY, USA",
        website: "https://www.jpmorganchase.com",
        founded: "1799",
      },
      jobs: [
        {
          title: "Investment Banker",
          slug: "investment-banker-jpmorgan",
          description: "Provide financial advisory services to clients.",
          requirements: ["MBA", "CFA certification", "7+ years experience"],
          responsibilities: ["Advise on mergers", "Raise capital", "Manage portfolios"],
          benefits: ["Competitive salary", "Bonuses", "Health benefits"],
          skills: ["Finance", "Investment", "Advisory"],
          type: "FULL_TIME",
          experience: "7-10 years",
          salary: "$150,000 - $250,000",
          location: "New York, NY, USA",
          isRemote: false,
          deadline: new Date("2025-12-15"),
          category: "Banking & Finance",
        },
        {
          title: "Financial Analyst",
          slug: "financial-analyst-jpmorgan",
          description: "Analyze financial data and provide insights.",
          requirements: ["Bachelor's in Finance", "2+ years experience", "Excel proficiency"],
          responsibilities: ["Analyze data", "Prepare reports", "Support decisions"],
          benefits: ["Competitive salary", "Bonuses", "Health benefits"],
          skills: ["Analysis", "Excel", "Finance"],
          type: "FULL_TIME",
          experience: "2-4 years",
          salary: "$70,000 - $100,000",
          location: "New York, NY, USA",
          isRemote: true,
          deadline: new Date("2025-11-20"),
          category: "Banking & Finance",
        },
      ],
    },
    {
      user: {
        email: "mike.johnson@bechtel.com",
        name: "Mike Johnson",
        image: "https://via.placeholder.com/150/00FF00/FFFFFF?text=MJ",
        phone: "+1-703-555-6789",
        location: "Reston, Virginia, USA",
        bio: "Construction industry recruiter specializing in engineering roles.",
        skills: ["Construction", "Engineering", "Recruitment"],
        experience: "15+ years in construction HR",
        education: "MS in Civil Engineering",
      },
      company: {
        name: "Bechtel",
        slug: "bechtel",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Bechtel-Logo.png",
        description: "Bechtel is a global engineering, construction, and project management company.",
        industry: "Construction",
        size: "5000+",
        location: "Reston, Virginia, USA",
        website: "https://www.bechtel.com",
        founded: "1898",
      },
      jobs: [
        {
          title: "Project Manager",
          slug: "project-manager-bechtel",
          description: "Manage large-scale construction projects.",
          requirements: ["PMP certification", "10+ years experience", "Leadership skills"],
          responsibilities: ["Oversee projects", "Coordinate teams", "Ensure safety"],
          benefits: ["High salary", "Bonuses", "Travel opportunities"],
          skills: ["Project Management", "Construction", "Leadership"],
          type: "FULL_TIME",
          experience: "10+ years",
          salary: "$120,000 - $180,000",
          location: "Reston, Virginia, USA",
          isRemote: false,
          deadline: new Date("2025-12-20"),
          category: "Engineering",
        },
        {
          title: "Civil Engineer",
          slug: "civil-engineer-bechtel",
          description: "Design and oversee civil engineering projects.",
          requirements: ["Bachelor's in Civil Engineering", "5+ years experience", "AutoCAD"],
          responsibilities: ["Design structures", "Inspect sites", "Prepare plans"],
          benefits: ["Health insurance", "Retirement", "Paid leave"],
          skills: ["Civil Engineering", "AutoCAD", "Design"],
          type: "FULL_TIME",
          experience: "5-8 years",
          salary: "$80,000 - $110,000",
          location: "Reston, Virginia, USA",
          isRemote: false,
          deadline: new Date("2025-11-25"),
          category: "Engineering",
        },
      ],
    },
    {
      user: {
        email: "sarah.wilson@mckinsey.com",
        name: "Sarah Wilson",
        image: "https://via.placeholder.com/150/FFFF00/000000?text=SW",
        phone: "+1-212-555-9876",
        location: "New York, NY, USA",
        bio: "Consulting recruiter with expertise in strategy and management.",
        skills: ["Consulting", "Strategy", "Recruitment"],
        experience: "8+ years in consulting HR",
        education: "MBA from Harvard Business School",
      },
      company: {
        name: "McKinsey & Company",
        slug: "mckinsey-company",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/McKinsey-Logo.png",
        description: "McKinsey & Company is a global management consulting firm.",
        industry: "Consulting",
        size: "5000+",
        location: "New York, NY, USA",
        website: "https://www.mckinsey.com",
        founded: "1926",
      },
      jobs: [
        {
          title: "Management Consultant",
          slug: "management-consultant-mckinsey",
          description: "Provide strategic advice to clients.",
          requirements: ["MBA", "3+ years experience", "Analytical skills"],
          responsibilities: ["Analyze problems", "Develop solutions", "Present findings"],
          benefits: ["High compensation", "Travel", "Professional development"],
          skills: ["Consulting", "Analysis", "Strategy"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "$120,000 - $200,000",
          location: "New York, NY, USA",
          isRemote: false,
          deadline: new Date("2025-12-10"),
          category: "Consulting",
        },
        {
          title: "Business Analyst",
          slug: "business-analyst-mckinsey",
          description: "Support consulting projects with data analysis.",
          requirements: ["Bachelor's in Business", "2+ years experience", "Data skills"],
          responsibilities: ["Collect data", "Analyze trends", "Support teams"],
          benefits: ["Competitive pay", "Bonuses", "Health benefits"],
          skills: ["Analysis", "Data", "Business"],
          type: "FULL_TIME",
          experience: "2-4 years",
          salary: "$80,000 - $120,000",
          location: "New York, NY, USA",
          isRemote: true,
          deadline: new Date("2025-11-15"),
          category: "Analytics",
        },
      ],
    },
    {
      user: {
        email: "alex.brown@palantir.com",
        name: "Alex Brown",
        image: "https://via.placeholder.com/150/FF00FF/FFFFFF?text=AB",
        phone: "+1-650-555-4321",
        location: "Palo Alto, CA, USA",
        bio: "Data analytics recruiter for tech companies.",
        skills: ["Data Analytics", "Tech", "Recruitment"],
        experience: "6+ years in tech HR",
        education: "MS in Data Science",
      },
      company: {
        name: "Palantir",
        slug: "palantir",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Palantir-Logo.png",
        description: "Palantir builds software to help organizations integrate their data.",
        industry: "Data & Analytics",
        size: "1001-5000",
        location: "Palo Alto, CA, USA",
        website: "https://www.palantir.com",
        founded: "2003",
      },
      jobs: [
        {
          title: "Data Scientist",
          slug: "data-scientist-palantir",
          description: "Analyze large datasets to extract insights.",
          requirements: ["PhD in Data Science", "5+ years experience", "Python, R"],
          responsibilities: ["Build models", "Analyze data", "Present insights"],
          benefits: ["Stock options", "Health insurance", "Flexible work"],
          skills: ["Data Science", "Python", "Machine Learning"],
          type: "FULL_TIME",
          experience: "5-8 years",
          salary: "$150,000 - $220,000",
          location: "Palo Alto, CA, USA",
          isRemote: false,
          deadline: new Date("2025-12-05"),
          category: "Analytics",
        },
        {
          title: "Software Engineer - Data",
          slug: "software-engineer-data-palantir",
          description: "Develop software for data processing.",
          requirements: ["Bachelor's in CS", "3+ years experience", "Java, Scala"],
          responsibilities: ["Write code", "Debug issues", "Collaborate"],
          benefits: ["Competitive salary", "Equity", "Health benefits"],
          skills: ["Software Engineering", "Java", "Data"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "$120,000 - $180,000",
          location: "Palo Alto, CA, USA",
          isRemote: true,
          deadline: new Date("2025-11-10"),
          category: "Software & IT",
        },
      ],
    },
    {
      user: {
        email: "emma.davis@amazon.com",
        name: "Emma Davis",
        image: "https://via.placeholder.com/150/00FFFF/000000?text=ED",
        phone: "+1-206-555-8765",
        location: "Seattle, WA, USA",
        bio: "E-commerce recruiter with focus on retail and logistics.",
        skills: ["E-commerce", "Retail", "Recruitment"],
        experience: "9+ years in e-commerce HR",
        education: "MBA from University of Washington",
      },
      company: {
        name: "Amazon",
        slug: "amazon",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Amazon-Logo.png",
        description: "Amazon is a multinational technology company focusing on e-commerce.",
        industry: "E-commerce",
        size: "5000+",
        location: "Seattle, WA, USA",
        website: "https://www.amazon.com",
        founded: "1994",
      },
      jobs: [
        {
          title: "Product Manager",
          slug: "product-manager-amazon",
          description: "Manage product development in e-commerce.",
          requirements: ["MBA", "5+ years experience", "Product knowledge"],
          responsibilities: ["Define products", "Work with teams", "Analyze metrics"],
          benefits: ["Stock awards", "Health", "Work-life balance"],
          skills: ["Product Management", "E-commerce", "Analytics"],
          type: "FULL_TIME",
          experience: "5-7 years",
          salary: "$130,000 - $200,000",
          location: "Seattle, WA, USA",
          isRemote: false,
          deadline: new Date("2025-12-25"),
          category: "Software & IT",
        },
        {
          title: "Operations Manager",
          slug: "operations-manager-amazon",
          description: "Oversee warehouse and logistics operations.",
          requirements: ["Bachelor's in Business", "4+ years experience", "Leadership"],
          responsibilities: ["Manage teams", "Optimize processes", "Ensure efficiency"],
          benefits: ["Competitive pay", "Bonuses", "Health benefits"],
          skills: ["Operations", "Logistics", "Management"],
          type: "FULL_TIME",
          experience: "4-6 years",
          salary: "$90,000 - $130,000",
          location: "Seattle, WA, USA",
          isRemote: false,
          deadline: new Date("2025-11-30"),
          category: "Logistics",
        },
      ],
    },
    {
      user: {
        email: "liam.garcia@coursera.com",
        name: "Liam Garcia",
        image: "https://via.placeholder.com/150/800080/FFFFFF?text=LG",
        phone: "+1-650-555-3456",
        location: "Mountain View, CA, USA",
        bio: "Education technology recruiter.",
        skills: ["Education", "Tech", "Recruitment"],
        experience: "7+ years in edtech HR",
        education: "MS in Education Technology",
      },
      company: {
        name: "Coursera",
        slug: "coursera",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Coursera-Logo.png",
        description: "Coursera provides online courses from universities.",
        industry: "Education",
        size: "1001-5000",
        location: "Mountain View, CA, USA",
        website: "https://www.coursera.org",
        founded: "2012",
      },
      jobs: [
        {
          title: "Content Developer",
          slug: "content-developer-coursera",
          description: "Create educational content for online courses.",
          requirements: ["Master's degree", "3+ years experience", "Teaching skills"],
          responsibilities: ["Develop courses", "Collaborate with instructors", "Review content"],
          benefits: ["Flexible hours", "Health insurance", "Professional growth"],
          skills: ["Content Creation", "Education", "Teaching"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "$70,000 - $100,000",
          location: "Mountain View, CA, USA",
          isRemote: true,
          deadline: new Date("2025-12-01"),
          category: "Education",
        },
        {
          title: "Marketing Specialist",
          slug: "marketing-specialist-coursera",
          description: "Promote online learning platforms.",
          requirements: ["Bachelor's in Marketing", "2+ years experience", "Digital marketing"],
          responsibilities: ["Create campaigns", "Analyze performance", "Engage users"],
          benefits: ["Competitive salary", "Bonuses", "Health benefits"],
          skills: ["Marketing", "Digital", "Analytics"],
          type: "FULL_TIME",
          experience: "2-4 years",
          salary: "$60,000 - $90,000",
          location: "Mountain View, CA, USA",
          isRemote: true,
          deadline: new Date("2025-11-05"),
          category: "Marketing",
        },
      ],
    },
    {
      user: {
        email: "olivia.martinez@wwf.org",
        name: "Olivia Martinez",
        image: "https://via.placeholder.com/150/008000/FFFFFF?text=OM",
        phone: "+41-22-555-7890",
        location: "Gland, Switzerland",
        bio: "Environmental conservation recruiter.",
        skills: ["Environment", "Conservation", "Recruitment"],
        experience: "10+ years in non-profit HR",
        education: "MS in Environmental Science",
      },
      company: {
        name: "WWF",
        slug: "wwf",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/WWF-Logo.png",
        description: "World Wildlife Fund works for conservation of nature.",
        industry: "Environment & Conservation",
        size: "1001-5000",
        location: "Gland, Switzerland",
        website: "https://www.worldwildlife.org",
        founded: "1961",
      },
      jobs: [
        {
          title: "Conservation Scientist",
          slug: "conservation-scientist-wwf",
          description: "Conduct research on wildlife conservation.",
          requirements: ["PhD in Biology", "5+ years experience", "Field work"],
          responsibilities: ["Research species", "Develop strategies", "Publish findings"],
          benefits: ["Meaningful work", "Travel", "Health benefits"],
          skills: ["Research", "Biology", "Conservation"],
          type: "FULL_TIME",
          experience: "5-8 years",
          salary: "€60,000 - €90,000",
          location: "Gland, Switzerland",
          isRemote: false,
          deadline: new Date("2025-12-15"),
          category: "Environment & Conservation",
        },
        {
          title: "Program Coordinator",
          slug: "program-coordinator-wwf",
          description: "Coordinate conservation programs.",
          requirements: ["Bachelor's in Environmental Science", "3+ years experience", "Project management"],
          responsibilities: ["Manage projects", "Coordinate teams", "Report progress"],
          benefits: ["Flexible work", "Health insurance", "Paid leave"],
          skills: ["Project Management", "Coordination", "Environment"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "€45,000 - €65,000",
          location: "Gland, Switzerland",
          isRemote: true,
          deadline: new Date("2025-11-20"),
          category: "Non-Profit",
        },
      ],
    },
    {
      user: {
        email: "noah.rodriguez@alibaba.com",
        name: "Noah Rodriguez",
        image: "https://via.placeholder.com/150/FFA500/000000?text=NR",
        phone: "+86-571-555-2345",
        location: "Hangzhou, China",
        bio: "Export and trade recruiter for global commerce.",
        skills: ["Export", "Trade", "Recruitment"],
        experience: "11+ years in international trade HR",
        education: "MBA from Peking University",
      },
      company: {
        name: "Alibaba",
        slug: "alibaba",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Alibaba-Logo.png",
        description: "Alibaba is a Chinese multinational conglomerate specializing in e-commerce.",
        industry: "Export & Trade",
        size: "5000+",
        location: "Hangzhou, China",
        website: "https://www.alibaba.com",
        founded: "1999",
      },
      jobs: [
        {
          title: "Supply Chain Manager",
          slug: "supply-chain-manager-alibaba",
          description: "Manage global supply chains for e-commerce.",
          requirements: ["MBA", "7+ years experience", "Supply chain knowledge"],
          responsibilities: ["Optimize logistics", "Negotiate suppliers", "Ensure delivery"],
          benefits: ["High salary", "Stock options", "International travel"],
          skills: ["Supply Chain", "Logistics", "Management"],
          type: "FULL_TIME",
          experience: "7-10 years",
          salary: "¥500,000 - ¥800,000",
          location: "Hangzhou, China",
          isRemote: false,
          deadline: new Date("2025-12-20"),
          category: "Logistics",
        },
        {
          title: "Business Development Manager",
          slug: "business-development-manager-alibaba",
          description: "Expand business in international markets.",
          requirements: ["Bachelor's in Business", "4+ years experience", "Negotiation skills"],
          responsibilities: ["Identify opportunities", "Build partnerships", "Drive sales"],
          benefits: ["Commission", "Bonuses", "Health benefits"],
          skills: ["Business Development", "Sales", "Negotiation"],
          type: "FULL_TIME",
          experience: "4-6 years",
          salary: "¥300,000 - ¥500,000",
          location: "Hangzhou, China",
          isRemote: true,
          deadline: new Date("2025-11-25"),
          category: "Sales",
        },
      ],
    },
    {
      user: {
        email: "ava.lopez@goldmansachs.com",
        name: "Ava Lopez",
        image: "https://via.placeholder.com/150/800000/FFFFFF?text=AL",
        phone: "+1-212-555-6543",
        location: "New York, NY, USA",
        bio: "Finance recruiter at a top investment bank.",
        skills: ["Finance", "Investment", "Recruitment"],
        experience: "13+ years in finance HR",
        education: "MBA from Wharton",
      },
      company: {
        name: "Goldman Sachs",
        slug: "goldman-sachs",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Goldman-Sachs-Logo.png",
        description: "Goldman Sachs is a leading investment banking firm.",
        industry: "Finance",
        size: "5000+",
        location: "New York, NY, USA",
        website: "https://www.goldmansachs.com",
        founded: "1869",
      },
      jobs: [
        {
          title: "Equity Research Analyst",
          slug: "equity-research-analyst-goldman",
          description: "Analyze stocks and provide investment recommendations.",
          requirements: ["MBA or CFA", "3+ years experience", "Financial modeling"],
          responsibilities: ["Research companies", "Write reports", "Present to clients"],
          benefits: ["High bonuses", "Health insurance", "Retirement"],
          skills: ["Research", "Finance", "Analysis"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "$120,000 - $180,000",
          location: "New York, NY, USA",
          isRemote: false,
          deadline: new Date("2025-12-10"),
          category: "Banking & Finance",
        },
        {
          title: "Risk Manager",
          slug: "risk-manager-goldman",
          description: "Assess and manage financial risks.",
          requirements: ["Master's in Finance", "5+ years experience", "Risk modeling"],
          responsibilities: ["Assess risks", "Develop strategies", "Monitor portfolios"],
          benefits: ["Competitive pay", "Bonuses", "Health benefits"],
          skills: ["Risk Management", "Finance", "Modeling"],
          type: "FULL_TIME",
          experience: "5-7 years",
          salary: "$140,000 - $200,000",
          location: "New York, NY, USA",
          isRemote: false,
          deadline: new Date("2025-11-15"),
          category: "Banking & Finance",
        },
      ],
    },
    {
      user: {
        email: "william.gonzalez@stripe.com",
        name: "William Gonzalez",
        image: "https://via.placeholder.com/150/000080/FFFFFF?text=WG",
        phone: "+1-415-555-7890",
        location: "San Francisco, CA, USA",
        bio: "Fintech recruiter for payment solutions.",
        skills: ["Fintech", "Payments", "Recruitment"],
        experience: "8+ years in fintech HR",
        education: "MS in Computer Science",
      },
      company: {
        name: "Stripe",
        slug: "stripe",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Stripe-Logo.png",
        description: "Stripe is a technology company that builds economic infrastructure for the internet.",
        industry: "Fintech",
        size: "1001-5000",
        location: "San Francisco, CA, USA",
        website: "https://stripe.com",
        founded: "2010",
      },
      jobs: [
        {
          title: "Software Engineer - Payments",
          slug: "software-engineer-payments-stripe",
          description: "Develop payment processing software.",
          requirements: ["Bachelor's in CS", "4+ years experience", "Go, Ruby"],
          responsibilities: ["Build features", "Ensure security", "Scale systems"],
          benefits: ["Equity", "Health insurance", "Flexible work"],
          skills: ["Software Engineering", "Payments", "Security"],
          type: "FULL_TIME",
          experience: "4-6 years",
          salary: "$150,000 - $220,000",
          location: "San Francisco, CA, USA",
          isRemote: true,
          deadline: new Date("2025-12-05"),
          category: "Software & IT",
        },
        {
          title: "Product Designer",
          slug: "product-designer-stripe",
          description: "Design user interfaces for fintech products.",
          requirements: ["Bachelor's in Design", "3+ years experience", "UI/UX tools"],
          responsibilities: ["Design interfaces", "Conduct research", "Collaborate with teams"],
          benefits: ["Creative work", "Health benefits", "Equity"],
          skills: ["Design", "UI/UX", "Fintech"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "$120,000 - $170,000",
          location: "San Francisco, CA, USA",
          isRemote: true,
          deadline: new Date("2025-11-10"),
          category: "Software & IT",
        },
      ],
    },
    {
      user: {
        email: "sophia.lee@pfizer.com",
        name: "Sophia Lee",
        image: "https://via.placeholder.com/150/FFC0CB/000000?text=SL",
        phone: "+1-212-555-3456",
        location: "New York, NY, USA",
        bio: "Healthcare recruiter for pharmaceutical company.",
        skills: ["Healthcare", "Pharma", "Recruitment"],
        experience: "12+ years in healthcare HR",
        education: "PhD in Pharmacology",
      },
      company: {
        name: "Pfizer",
        slug: "pfizer",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Pfizer-Logo.png",
        description: "Pfizer is a multinational pharmaceutical corporation.",
        industry: "Healthcare",
        size: "5000+",
        location: "New York, NY, USA",
        website: "https://www.pfizer.com",
        founded: "1849",
      },
      jobs: [
        {
          title: "Clinical Research Scientist",
          slug: "clinical-research-scientist-pfizer",
          description: "Conduct clinical trials for new drugs.",
          requirements: ["PhD in Medicine", "5+ years experience", "Regulatory knowledge"],
          responsibilities: ["Design trials", "Analyze data", "Ensure compliance"],
          benefits: ["Research funding", "Health benefits", "Travel"],
          skills: ["Research", "Clinical", "Pharma"],
          type: "FULL_TIME",
          experience: "5-8 years",
          salary: "$130,000 - $180,000",
          location: "New York, NY, USA",
          isRemote: false,
          deadline: new Date("2025-12-25"),
          category: "Healthcare",
        },
        {
          title: "Regulatory Affairs Specialist",
          slug: "regulatory-affairs-specialist-pfizer",
          description: "Manage regulatory compliance for products.",
          requirements: ["Master's in Regulatory Affairs", "4+ years experience", "FDA knowledge"],
          responsibilities: ["Prepare submissions", "Liaise with agencies", "Ensure compliance"],
          benefits: ["Stable job", "Health insurance", "Paid leave"],
          skills: ["Regulatory", "Compliance", "Pharma"],
          type: "FULL_TIME",
          experience: "4-6 years",
          salary: "$100,000 - $140,000",
          location: "New York, NY, USA",
          isRemote: false,
          deadline: new Date("2025-11-30"),
          category: "Healthcare",
        },
      ],
    },
    {
      user: {
        email: "james.wang@marriott.com",
        name: "James Wang",
        image: "https://via.placeholder.com/150/FFFF00/000000?text=JW",
        phone: "+1-301-555-6789",
        location: "Bethesda, MD, USA",
        bio: "Hospitality recruiter for hotel chain.",
        skills: ["Hospitality", "Hotels", "Recruitment"],
        experience: "9+ years in hospitality HR",
        education: "MBA from Cornell",
      },
      company: {
        name: "Marriott International",
        slug: "marriott-international",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Marriott-Logo.png",
        description: "Marriott International is a multinational hospitality company.",
        industry: "Hospitality",
        size: "5000+",
        location: "Bethesda, MD, USA",
        website: "https://www.marriott.com",
        founded: "1927",
      },
      jobs: [
        {
          title: "Hotel Manager",
          slug: "hotel-manager-marriott",
          description: "Manage daily operations of hotels.",
          requirements: ["Bachelor's in Hospitality", "7+ years experience", "Leadership"],
          responsibilities: ["Oversee staff", "Ensure guest satisfaction", "Manage budgets"],
          benefits: ["Travel perks", "Health insurance", "Bonuses"],
          skills: ["Management", "Hospitality", "Leadership"],
          type: "FULL_TIME",
          experience: "7-10 years",
          salary: "$80,000 - $120,000",
          location: "Bethesda, MD, USA",
          isRemote: false,
          deadline: new Date("2025-12-01"),
          category: "Hospitality",
        },
        {
          title: "Event Coordinator",
          slug: "event-coordinator-marriott",
          description: "Organize events and conferences at hotels.",
          requirements: ["Bachelor's in Event Management", "3+ years experience", "Planning skills"],
          responsibilities: ["Plan events", "Coordinate vendors", "Manage logistics"],
          benefits: ["Creative work", "Health benefits", "Paid leave"],
          skills: ["Event Planning", "Coordination", "Hospitality"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "$50,000 - $70,000",
          location: "Bethesda, MD, USA",
          isRemote: false,
          deadline: new Date("2025-11-05"),
          category: "Hospitality",
        },
      ],
    },
    {
      user: {
        email: "mia.kim@dhl.com",
        name: "Mia Kim",
        image: "https://via.placeholder.com/150/FF69B4/000000?text=MK",
        phone: "+49-228-555-1234",
        location: "Bonn, Germany",
        bio: "Logistics recruiter for global shipping company.",
        skills: ["Logistics", "Shipping", "Recruitment"],
        experience: "10+ years in logistics HR",
        education: "MS in Supply Chain Management",
      },
      company: {
        name: "DHL",
        slug: "dhl",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/DHL-Logo.png",
        description: "DHL is a German multinational package delivery and supply chain management company.",
        industry: "Logistics",
        size: "5000+",
        location: "Bonn, Germany",
        website: "https://www.dhl.com",
        founded: "1969",
      },
      jobs: [
        {
          title: "Logistics Coordinator",
          slug: "logistics-coordinator-dhl",
          description: "Coordinate international shipments.",
          requirements: ["Bachelor's in Logistics", "4+ years experience", "SAP knowledge"],
          responsibilities: ["Track shipments", "Optimize routes", "Resolve issues"],
          benefits: ["Travel", "Health insurance", "Bonuses"],
          skills: ["Logistics", "Coordination", "SAP"],
          type: "FULL_TIME",
          experience: "4-6 years",
          salary: "€50,000 - €70,000",
          location: "Bonn, Germany",
          isRemote: false,
          deadline: new Date("2025-12-15"),
          category: "Logistics",
        },
        {
          title: "Supply Chain Analyst",
          slug: "supply-chain-analyst-dhl",
          description: "Analyze supply chain data for efficiency.",
          requirements: ["Bachelor's in Business", "3+ years experience", "Data analysis"],
          responsibilities: ["Analyze data", "Identify improvements", "Report findings"],
          benefits: ["Flexible work", "Health benefits", "Paid leave"],
          skills: ["Analysis", "Supply Chain", "Data"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "€45,000 - €65,000",
          location: "Bonn, Germany",
          isRemote: true,
          deadline: new Date("2025-11-20"),
          category: "Logistics",
        },
      ],
    },
    {
      user: {
        email: "benjamin.nguyen@toyota.com",
        name: "Benjamin Nguyen",
        image: "https://via.placeholder.com/150/32CD32/FFFFFF?text=BN",
        phone: "+81-565-555-7890",
        location: "Toyota City, Japan",
        bio: "Manufacturing recruiter for automotive company.",
        skills: ["Manufacturing", "Automotive", "Recruitment"],
        experience: "14+ years in manufacturing HR",
        education: "MS in Mechanical Engineering",
      },
      company: {
        name: "Toyota",
        slug: "toyota",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Toyota-Logo.png",
        description: "Toyota is a Japanese multinational automotive manufacturer.",
        industry: "Manufacturing",
        size: "5000+",
        location: "Toyota City, Japan",
        website: "https://www.toyota.com",
        founded: "1937",
      },
      jobs: [
        {
          title: "Mechanical Engineer",
          slug: "mechanical-engineer-toyota",
          description: "Design automotive components.",
          requirements: ["Bachelor's in Mechanical Engineering", "5+ years experience", "CAD"],
          responsibilities: ["Design parts", "Test prototypes", "Improve efficiency"],
          benefits: ["Innovation focus", "Health insurance", "Retirement"],
          skills: ["Engineering", "CAD", "Automotive"],
          type: "FULL_TIME",
          experience: "5-8 years",
          salary: "¥6,000,000 - ¥9,000,000",
          location: "Toyota City, Japan",
          isRemote: false,
          deadline: new Date("2025-12-20"),
          category: "Engineering",
        },
        {
          title: "Quality Control Inspector",
          slug: "quality-control-inspector-toyota",
          description: "Ensure product quality in manufacturing.",
          requirements: ["Associate's degree", "3+ years experience", "Attention to detail"],
          responsibilities: ["Inspect products", "Report defects", "Maintain standards"],
          benefits: ["Stable job", "Health benefits", "Paid leave"],
          skills: ["Quality Control", "Inspection", "Manufacturing"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "¥4,000,000 - ¥6,000,000",
          location: "Toyota City, Japan",
          isRemote: false,
          deadline: new Date("2025-11-25"),
          category: "Manufacturing",
        },
      ],
    },
    {
      user: {
        email: "charlotte.patel@wpp.com",
        name: "Charlotte Patel",
        image: "https://via.placeholder.com/150/DC143C/FFFFFF?text=CP",
        phone: "+44-20-555-6543",
        location: "London, UK",
        bio: "Marketing and advertising recruiter.",
        skills: ["Marketing", "Advertising", "Recruitment"],
        experience: "11+ years in marketing HR",
        education: "MBA from London Business School",
      },
      company: {
        name: "WPP",
        slug: "wpp",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/WPP-Logo.png",
        description: "WPP is a British multinational communications, advertising and public relations company.",
        industry: "Marketing & Advertising",
        size: "5000+",
        location: "London, UK",
        website: "https://www.wpp.com",
        founded: "1985",
      },
      jobs: [
        {
          title: "Creative Director",
          slug: "creative-director-wpp",
          description: "Lead creative campaigns for clients.",
          requirements: ["Bachelor's in Design", "8+ years experience", "Portfolio"],
          responsibilities: ["Develop concepts", "Manage teams", "Present to clients"],
          benefits: ["Creative freedom", "High bonuses", "Travel"],
          skills: ["Creativity", "Design", "Leadership"],
          type: "FULL_TIME",
          experience: "8-12 years",
          salary: "£80,000 - £120,000",
          location: "London, UK",
          isRemote: false,
          deadline: new Date("2025-12-10"),
          category: "Marketing",
        },
        {
          title: "Digital Marketing Specialist",
          slug: "digital-marketing-specialist-wpp",
          description: "Manage digital marketing campaigns.",
          requirements: ["Bachelor's in Marketing", "4+ years experience", "Google Ads"],
          responsibilities: ["Create campaigns", "Analyze performance", "Optimize strategies"],
          benefits: ["Dynamic work", "Health benefits", "Bonuses"],
          skills: ["Digital Marketing", "Ads", "Analytics"],
          type: "FULL_TIME",
          experience: "4-6 years",
          salary: "£50,000 - £70,000",
          location: "London, UK",
          isRemote: true,
          deadline: new Date("2025-11-15"),
          category: "Marketing",
        },
      ],
    },
    {
      user: {
        email: "lucas.sanchez@medtronic.com",
        name: "Lucas Sanchez",
        image: "https://via.placeholder.com/150/8A2BE2/FFFFFF?text=LS",
        phone: "+1-763-555-2345",
        location: "Minneapolis, MN, USA",
        bio: "Medical supplies recruiter for medical devices.",
        skills: ["Medical Supplies", "Devices", "Recruitment"],
        experience: "10+ years in medical HR",
        education: "MS in Biomedical Engineering",
      },
      company: {
        name: "Medtronic",
        slug: "medtronic",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Medtronic-Logo.png",
        description: "Medtronic is a medical device company.",
        industry: "Medical Supplies",
        size: "5000+",
        location: "Minneapolis, MN, USA",
        website: "https://www.medtronic.com",
        founded: "1949",
      },
      jobs: [
        {
          title: "Biomedical Engineer",
          slug: "biomedical-engineer-medtronic",
          description: "Design medical devices.",
          requirements: ["Bachelor's in Biomedical Engineering", "5+ years experience", "FDA regulations"],
          responsibilities: ["Design devices", "Test safety", "Collaborate with doctors"],
          benefits: ["Innovation", "Health insurance", "Retirement"],
          skills: ["Engineering", "Medical", "Design"],
          type: "FULL_TIME",
          experience: "5-8 years",
          salary: "$100,000 - $140,000",
          location: "Minneapolis, MN, USA",
          isRemote: false,
          deadline: new Date("2025-12-05"),
          category: "Healthcare",
        },
        {
          title: "Regulatory Compliance Officer",
          slug: "regulatory-compliance-officer-medtronic",
          description: "Ensure compliance with medical regulations.",
          requirements: ["Bachelor's in Regulatory Affairs", "4+ years experience", "Medical knowledge"],
          responsibilities: ["Monitor regulations", "Prepare documents", "Audit processes"],
          benefits: ["Stable career", "Health benefits", "Paid leave"],
          skills: ["Compliance", "Regulatory", "Medical"],
          type: "FULL_TIME",
          experience: "4-6 years",
          salary: "$80,000 - $110,000",
          location: "Minneapolis, MN, USA",
          isRemote: false,
          deadline: new Date("2025-11-10"),
          category: "Healthcare",
        },
      ],
    },
    {
      user: {
        email: "harper.taylor@redcross.org",
        name: "Harper Taylor",
        image: "https://via.placeholder.com/150/FF4500/FFFFFF?text=HT",
        phone: "+41-22-555-5678",
        location: "Geneva, Switzerland",
        bio: "Non-profit recruiter for humanitarian organization.",
        skills: ["Non-Profit", "Humanitarian", "Recruitment"],
        experience: "12+ years in non-profit HR",
        education: "MS in International Relations",
      },
      company: {
        name: "Red Cross",
        slug: "red-cross",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Red-Cross-Logo.png",
        description: "The Red Cross is an international humanitarian organization.",
        industry: "Non-Profit",
        size: "5000+",
        location: "Geneva, Switzerland",
        website: "https://www.redcross.org",
        founded: "1863",
      },
      jobs: [
        {
          title: "Program Manager",
          slug: "program-manager-red-cross",
          description: "Manage humanitarian programs.",
          requirements: ["Master's in Humanitarian Aid", "6+ years experience", "Project management"],
          responsibilities: ["Plan programs", "Coordinate aid", "Report impact"],
          benefits: ["Meaningful work", "Travel", "Health benefits"],
          skills: ["Program Management", "Humanitarian", "Coordination"],
          type: "FULL_TIME",
          experience: "6-9 years",
          salary: "€60,000 - €85,000",
          location: "Geneva, Switzerland",
          isRemote: false,
          deadline: new Date("2025-12-25"),
          category: "Non-Profit",
        },
        {
          title: "Fundraiser",
          slug: "fundraiser-red-cross",
          description: "Raise funds for humanitarian causes.",
          requirements: ["Bachelor's in Communications", "3+ years experience", "Networking"],
          responsibilities: ["Develop campaigns", "Engage donors", "Track donations"],
          benefits: ["Flexible hours", "Health insurance", "Paid leave"],
          skills: ["Fundraising", "Communications", "Networking"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "€45,000 - €65,000",
          location: "Geneva, Switzerland",
          isRemote: true,
          deadline: new Date("2025-11-30"),
          category: "Non-Profit",
        },
      ],
    },
    {
      user: {
        email: "mason.anderson@walmart.com",
        name: "Mason Anderson",
        image: "https://via.placeholder.com/150/2E8B57/FFFFFF?text=MA",
        phone: "+1-479-555-8901",
        location: "Bentonville, AR, USA",
        bio: "Retail recruiter for multinational retailer.",
        skills: ["Retail", "Sales", "Recruitment"],
        experience: "15+ years in retail HR",
        education: "MBA from University of Arkansas",
      },
      company: {
        name: "Walmart",
        slug: "walmart",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Walmart-Logo.png",
        description: "Walmart is an American multinational retail corporation.",
        industry: "Retail",
        size: "5000+",
        location: "Bentonville, AR, USA",
        website: "https://www.walmart.com",
        founded: "1962",
      },
      jobs: [
        {
          title: "Store Manager",
          slug: "store-manager-walmart",
          description: "Manage retail store operations.",
          requirements: ["Bachelor's in Business", "5+ years experience", "Leadership"],
          responsibilities: ["Oversee staff", "Manage inventory", "Ensure customer satisfaction"],
          benefits: ["Employee discounts", "Health insurance", "Bonuses"],
          skills: ["Management", "Retail", "Leadership"],
          type: "FULL_TIME",
          experience: "5-7 years",
          salary: "$70,000 - $100,000",
          location: "Bentonville, AR, USA",
          isRemote: false,
          deadline: new Date("2025-12-01"),
          category: "Retail",
        },
        {
          title: "Buyer",
          slug: "buyer-walmart",
          description: "Purchase products for retail stores.",
          requirements: ["Bachelor's in Business", "3+ years experience", "Negotiation"],
          responsibilities: ["Negotiate prices", "Select products", "Manage suppliers"],
          benefits: ["Travel", "Health benefits", "Paid leave"],
          skills: ["Buying", "Negotiation", "Retail"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "$60,000 - $80,000",
          location: "Bentonville, AR, USA",
          isRemote: false,
          deadline: new Date("2025-11-05"),
          category: "Retail",
        },
      ],
    },
    {
      user: {
        email: "ella.thomas@google.com",
        name: "Ella Thomas",
        image: "https://via.placeholder.com/150/4682B4/FFFFFF?text=ET",
        phone: "+1-650-555-4321",
        location: "Mountain View, CA, USA",
        bio: "Technology recruiter for search engine giant.",
        skills: ["Technology", "Software", "Recruitment"],
        experience: "10+ years in tech HR",
        education: "MS in Computer Science",
      },
      company: {
        name: "Google",
        slug: "google",
        logo: "https://logos-world.net/wp-content/uploads/2020/12/Google-Logo.png",
        description: "Google is an American multinational technology company.",
        industry: "Technology",
        size: "5000+",
        location: "Mountain View, CA, USA",
        website: "https://www.google.com",
        founded: "1998",
      },
      jobs: [
        {
          title: "Software Engineer",
          slug: "software-engineer-google",
          description: "Develop software for Google's products.",
          requirements: ["Bachelor's in CS", "3+ years experience", "Algorithms"],
          responsibilities: ["Write code", "Debug", "Collaborate"],
          benefits: ["Perks", "Health insurance", "Equity"],
          skills: ["Software Engineering", "Algorithms", "Coding"],
          type: "FULL_TIME",
          experience: "3-5 years",
          salary: "$150,000 - $250,000",
          location: "Mountain View, CA, USA",
          isRemote: true,
          deadline: new Date("2025-12-15"),
          category: "Software & IT",
        },
        {
          title: "Data Analyst",
          slug: "data-analyst-google",
          description: "Analyze data to improve products.",
          requirements: ["Bachelor's in Statistics", "2+ years experience", "SQL"],
          responsibilities: ["Query data", "Create reports", "Insights"],
          benefits: ["Flexible work", "Health benefits", "Bonuses"],
          skills: ["Data Analysis", "SQL", "Statistics"],
          type: "FULL_TIME",
          experience: "2-4 years",
          salary: "$100,000 - $140,000",
          location: "Mountain View, CA, USA",
          isRemote: true,
          deadline: new Date("2025-11-20"),
          category: "Analytics",
        },
      ],
    },
  ];

  for (const recruiter of recruitersData) {
    const user = await prisma.user.create({
      data: {
        email: recruiter.user.email,
        password: hashedPassword,
        name: recruiter.user.name,
        role: 'RECRUITER',
        image: recruiter.user.image,
        phone: recruiter.user.phone,
        location: recruiter.user.location,
        bio: recruiter.user.bio,
        skills: recruiter.user.skills,
        experience: recruiter.user.experience,
        education: recruiter.user.education,
        resume: null,
      },
    });

    const company = await prisma.company.create({
      data: {
        name: recruiter.company.name,
        slug: recruiter.company.slug,
        logo: recruiter.company.logo,
        description: recruiter.company.description,
        industry: recruiter.company.industry,
        size: recruiter.company.size,
        location: recruiter.company.location,
        website: recruiter.company.website,
        founded: recruiter.company.founded,
        recruiterId: user.id,
      },
    });

    for (const job of recruiter.jobs) {
      await prisma.job.create({
        data: {
          title: job.title,
          slug: job.slug,
          description: job.description,
          requirements: job.requirements,
          responsibilities: job.responsibilities,
          benefits: job.benefits,
          skills: job.skills,
          type: job.type,
          experience: job.experience,
          salary: job.salary,
          location: job.location,
          isRemote: job.isRemote,
          deadline: job.deadline,
          category: job.category,
          recruiterId: user.id,
          companyId: company.id,
        },
      });
    }
  }

  console.log('Seeded 20 recruiters with companies and 2 jobs each.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
