export const INDUSTRY_OPTIONS = [
  { label: "Agriculture", value: "Agriculture" },
  { label: "Banking & Finance", value: "Banking & Finance" },
  { label: "Construction", value: "Construction" },
  { label: "Consulting", value: "Consulting" },
  { label: "Data & Analytics", value: "Data & Analytics" },
  { label: "E-commerce", value: "E-commerce" },
  { label: "Education", value: "Education" },
  { label: "Environment & Conservation", value: "Environment & Conservation" },
  { label: "Export & Trade", value: "Export & Trade" },
  { label: "Finance", value: "Finance" },
  { label: "Fintech", value: "Fintech" },
  { label: "Healthcare", value: "Healthcare" },
  { label: "Hospitality", value: "Hospitality" },
  { label: "Logistics", value: "Logistics" },
  { label: "Manufacturing", value: "Manufacturing" },
  { label: "Marketing & Advertising", value: "Marketing & Advertising" },
  { label: "Medical Supplies", value: "Medical Supplies" },
  { label: "Non-Profit", value: "Non-Profit" },
  { label: "Retail", value: "Retail" },
  { label: "Technology", value: "Technology" },
  { label: "Telecommunications", value: "Telecommunications" },
  { label: "Textiles", value: "Textiles" },
  { label: "Travel & Tourism", value: "Travel & Tourism" },
  { label: "Other", value: "Other" },
]

export const COMPANY_SIZE_OPTIONS = [
  { label: "1-10", value: "1-10" },
  { label: "11-50", value: "11-50" },
  { label: "51-200", value: "51-200" },
  { label: "201-500", value: "201-500" },
  { label: "501-1000", value: "501-1000" },
  { label: "1001-5000", value: "1001-5000" },
  { label: "5000+", value: "5000+" },
]
