import type { LucideIcon } from "lucide-react"
import {
  Code,
  Database,
  Cloud,
  Smartphone,
  Shield,
  Brain,
  Server,
  Globe,
  Cpu,
  Palette,
  BarChart,
  MessageSquare,
  Search,
  Wrench,
  Users,
  FileCode,
  GitBranch,
  LineChart,
  PieChart,
  Layout,
  Boxes,
  Network,
  Binary,
  Terminal,
  Layers,
  Cog,
  Zap,
  Package,
  Briefcase,
  TrendingUp,
  Target,
  Headphones,
  PenTool,
  Film,
  Music,
  Image as ImageIcon,
  BookOpen,
  GraduationCap,
  Megaphone,
  FileText,
  Calculator,
  Lock,
  Unlock,
  Workflow,
  GitMerge,
  Rocket,
  Microscope,
  FlaskConical,
  Lightbulb,
  ChartBar,
  Activity,
  Settings,
  Puzzle,
  Blocks,
} from "lucide-react"

export const SKILL_ICON_MAP: Record<string, LucideIcon> = {
  // Frontend & Web Development
  React: Code,
  "React Native": Smartphone,
  Vue: Code,
  Angular: Code,
  "Next.js": Code,
  Nuxt: Code,
  Svelte: Code,
  HTML: FileCode,
  CSS: Palette,
  JavaScript: Code,
  TypeScript: Code,
  jQuery: Code,
  Bootstrap: Layout,
  Tailwind: Palette,
  Sass: Palette,
  SCSS: Palette,
  Webpack: Package,
  Vite: Zap,
  Redux: Boxes,
  MobX: Boxes,

  // Backend & Server
  "Node.js": Server,
  Express: Server,
  NestJS: Server,
  Django: Server,
  Flask: Server,
  FastAPI: Zap,
  "Spring Boot": Server,
  "ASP.NET": Server,
  ".NET": Server,
  "Ruby on Rails": Server,
  Laravel: Server,
  PHP: Code,
  Go: Code,
  Rust: Code,
  Elixir: Code,

  // Programming Languages
  Python: Code,
  Java: Code,
  "C++": Code,
  "C#": Code,
  C: Code,
  Ruby: Code,
  Swift: Smartphone,
  Kotlin: Smartphone,
  Scala: Code,
  R: BarChart,
  MATLAB: Calculator,
  Perl: Code,
  Bash: Terminal,
  Shell: Terminal,
  PowerShell: Terminal,

  // Databases
  SQL: Database,
  MySQL: Database,
  PostgreSQL: Database,
  MongoDB: Database,
  Redis: Database,
  Cassandra: Database,
  DynamoDB: Database,
  Oracle: Database,
  "Microsoft SQL Server": Database,
  SQLite: Database,
  MariaDB: Database,
  Elasticsearch: Search,

  // Cloud & DevOps
  AWS: Cloud,
  Azure: Cloud,
  GCP: Cloud,
  "Google Cloud": Cloud,
  Docker: Cloud,
  Kubernetes: Cloud,
  Jenkins: Workflow,
  "CI/CD": Workflow,
  Terraform: Cloud,
  Ansible: Cog,
  Puppet: Cog,
  Chef: Cog,
  CircleCI: Workflow,
  "GitLab CI": GitBranch,
  "GitHub Actions": GitBranch,
  Heroku: Cloud,
  Vercel: Cloud,
  Netlify: Cloud,
  DigitalOcean: Cloud,

  // Version Control
  Git: GitBranch,
  GitHub: GitBranch,
  GitLab: GitBranch,
  Bitbucket: GitBranch,
  SVN: GitMerge,

  // Mobile Development
  iOS: Smartphone,
  Android: Smartphone,
  Flutter: Smartphone,
  Xamarin: Smartphone,
  Ionic: Smartphone,
  Cordova: Smartphone,

  // Data Science & AI/ML
  "Machine Learning": Brain,
  "Deep Learning": Brain,
  AI: Brain,
  "Artificial Intelligence": Brain,
  "Data Science": BarChart,
  "Data Analysis": LineChart,
  TensorFlow: Brain,
  PyTorch: Brain,
  Keras: Brain,
  "Scikit-learn": BarChart,
  Pandas: BarChart,
  NumPy: Calculator,
  "Natural Language Processing": MessageSquare,
  NLP: MessageSquare,
  "Computer Vision": Brain,
  "Neural Networks": Network,

  // Security
  Cybersecurity: Shield,
  Security: Shield,
  "Penetration Testing": Shield,
  "Ethical Hacking": Unlock,
  "Network Security": Network,
  "Information Security": Lock,
  SSL: Lock,
  OAuth: Lock,
  JWT: Lock,

  // Testing
  Jest: Puzzle,
  Mocha: Puzzle,
  Cypress: Puzzle,
  Selenium: Puzzle,
  JUnit: Puzzle,
  TestNG: Puzzle,
  PyTest: Puzzle,
  Testing: Puzzle,
  QA: Target,
  "Quality Assurance": Target,

  // Design & Creative
  "UI/UX": Palette,
  Figma: PenTool,
  "Adobe XD": PenTool,
  Photoshop: ImageIcon,
  Illustrator: Palette,
  Sketch: PenTool,
  InVision: Layout,
  "Graphic Design": Palette,
  "Video Editing": Film,
  Animation: Film,
  "3D Modeling": Blocks,

  // Business & Analytics
  "Business Analysis": BarChart,
  "Data Analytics": LineChart,
  "Power BI": PieChart,
  Tableau: BarChart,
  Excel: Calculator,
  "Google Analytics": LineChart,
  SEO: Search,
  SEM: Search,
  "Digital Marketing": Megaphone,
  "Content Marketing": FileText,
  "Social Media Marketing": MessageSquare,
  "Email Marketing": MessageSquare,
  "Market Research": Search,
  "Product Management": Briefcase,
  "Project Management": Target,
  Agile: Rocket,
  Scrum: Users,
  Jira: Workflow,
  Trello: Layout,
  Asana: Target,

  // Networking & Infrastructure
  Networking: Network,
  "TCP/IP": Network,
  DNS: Globe,
  Linux: Terminal,
  Unix: Terminal,
  "Windows Server": Server,
  VMware: Cloud,
  Virtualization: Layers,

  // Soft Skills & General
  Communication: MessageSquare,
  Leadership: Users,
  "Team Management": Users,
  "Problem Solving": Lightbulb,
  "Critical Thinking": Brain,
  Creativity: Palette,
  Research: Microscope,
  Writing: FileText,
  "Public Speaking": Megaphone,
  "Customer Service": Headphones,
  Sales: TrendingUp,
  Negotiation: Briefcase,
  "Time Management": Activity,
  Organization: Settings,
  Analysis: BarChart,
  Finance: Calculator,
  Design: Palette,
  Management: Briefcase,
  Coordination: Users,

  // Other Technologies
  GraphQL: Code,
  "REST API": Globe,
  API: Globe,
  Microservices: Layers,
  Blockchain: Blocks,
  IoT: Cpu,
  "Embedded Systems": Cpu,
  WebSocket: Network,
  gRPC: Network,
  RabbitMQ: Network,
  Kafka: Network,
  MQTT: Network,
  XML: FileCode,
  JSON: FileCode,
  YAML: FileCode,
}

// Default fallback icon
export const DEFAULT_SKILL_ICON = Code
