import type { Company, Job, Application, JobCategory, User, Notification, Interview } from "@/types"

export const mockCompanies: Company[] = [
  {
    id: "1",
    name: "TechCorp Solutions",
    logo: "/tech-company-logo.jpg",
    description: "Leading technology solutions provider specializing in cloud computing and AI.",
    industry: "Technology",
    size: "1000-5000",
    location: "San Francisco, CA",
    website: "https://techcorp.example.com",
    founded: "2010",
    jobCount: 3,
    rating: 4.5,
  },
  {
    id: "2",
    name: "DataFlow Analytics",
    logo: "/data-analytics-logo.jpg",
    description: "Data analytics and business intelligence platform for enterprises.",
    industry: "Data & Analytics",
    size: "500-1000",
    location: "New York, NY",
    website: "https://dataflow.example.com",
    founded: "2015",
    jobCount: 2,
    rating: 4.3,
  },
  {
    id: "3",
    name: "CloudNine Systems",
    logo: "/cloud-systems-logo.jpg",
    description: "Cloud infrastructure and DevOps solutions for modern businesses.",
    industry: "Cloud Computing",
    size: "200-500",
    location: "Austin, TX",
    website: "https://cloudnine.example.com",
    founded: "2018",
    jobCount: 2,
    rating: 4.7,
  },
  {
    id: "4",
    name: "FinTech Innovations",
    logo: "/fintech-logo.png",
    description: "Revolutionary financial technology solutions for the digital age.",
    industry: "Financial Services",
    size: "500-1000",
    location: "Boston, MA",
    founded: "2016",
    jobCount: 3,
    rating: 4.4,
  },
  {
    id: "5",
    name: "HealthTech Pro",
    logo: "/healthcare-tech-logo.jpg",
    description: "Healthcare technology platform improving patient care worldwide.",
    industry: "Healthcare",
    size: "1000-5000",
    location: "Seattle, WA",
    founded: "2012",
    jobCount: 52,
    rating: 4.6,
  },
  {
    id: "6",
    name: "EduLearn Platform",
    logo: "/education-platform-logo.png",
    description: "Online learning platform connecting students with quality education.",
    industry: "Education",
    size: "200-500",
    location: "Remote",
    founded: "2019",
    jobCount: 24,
    rating: 4.2,
  },
]

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: mockCompanies[0],
    location: "San Francisco, CA",
    type: "Full-time",
    experience: "5-7 years",
    salary: "$120k - $180k",
    description:
      "We are looking for an experienced Frontend Developer to join our dynamic team. You will be responsible for building scalable web applications using modern frameworks and best practices.",
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      "5+ years of experience with React, TypeScript, and Next.js",
      "Strong understanding of web performance optimization",
      "Experience with state management libraries (Redux, Zustand)",
      "Excellent problem-solving and communication skills",
    ],
    responsibilities: [
      "Develop and maintain high-quality web applications",
      "Collaborate with designers and backend developers",
      "Write clean, maintainable, and testable code",
      "Participate in code reviews and mentor junior developers",
      "Optimize applications for maximum speed and scalability",
    ],
    benefits: ["Health Insurance", "Remote Work", "401k", "Stock Options"],
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "GraphQL"],
    postedDate: new Date("2025-01-05"),
    applicants: 4,
    views: 320,
    featured: true,
    recruiterId: "rec1",
  },
  {
    id: "2",
    title: "Data Scientist",
    company: mockCompanies[1],
    location: "New York, NY",
    type: "Full-time",
    experience: "3-5 years",
    salary: "$100k - $150k",
    description:
      "Join our data science team to build predictive models and derive insights from large datasets. You will work on cutting-edge machine learning projects.",
    requirements: [
      "Master's degree in Data Science, Statistics, or related field",
      "3+ years of experience in data science or machine learning",
      "Proficiency in Python and SQL",
      "Experience with ML frameworks (TensorFlow, PyTorch, scikit-learn)",
      "Strong statistical analysis skills",
    ],
    responsibilities: [
      "Develop and deploy machine learning models",
      "Analyze large datasets to extract actionable insights",
      "Collaborate with product teams to define data requirements",
      "Create data visualizations and reports",
      "Stay updated with latest ML/AI trends",
    ],
    benefits: ["Health Insurance", "Learning Budget", "Flexible Hours"],
    skills: ["Python", "Machine Learning", "SQL", "TensorFlow", "Data Visualization"],
    postedDate: new Date("2025-01-04"),
    applicants: 2,
    views: 450,
    featured: true,
    recruiterId: "rec2",
  },
  {
    id: "3",
    title: "DevOps Engineer",
    company: mockCompanies[2],
    location: "Austin, TX",
    type: "Full-time",
    experience: "4-6 years",
    salary: "$110k - $160k",
    description:
      "We need a skilled DevOps Engineer to manage our cloud infrastructure and implement CI/CD pipelines for our growing platform.",
    requirements: [
      "Bachelor's degree in Computer Science or equivalent",
      "4+ years of DevOps experience",
      "Strong knowledge of AWS, Docker, and Kubernetes",
      "Experience with Infrastructure as Code (Terraform, CloudFormation)",
      "Proficiency in scripting languages (Python, Bash)",
    ],
    responsibilities: [
      "Design and maintain cloud infrastructure",
      "Implement and optimize CI/CD pipelines",
      "Monitor system performance and reliability",
      "Automate deployment processes",
      "Ensure security best practices",
    ],
    benefits: ["Health Insurance", "Remote Work", "Professional Development"],
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"],
    postedDate: new Date("2025-01-03"),
    applicants: 2,
    views: 280,
    featured: true,
    recruiterId: "rec3",
  },
  {
    id: "4",
    title: "Product Manager",
    company: mockCompanies[3],
    location: "Boston, MA",
    type: "Full-time",
    experience: "5-8 years",
    salary: "$130k - $190k",
    description:
      "Lead product strategy and execution for our fintech platform. Work with cross-functional teams to deliver innovative financial solutions.",
    requirements: [
      "Bachelor's degree in Business, Computer Science, or related field",
      "5+ years of product management experience",
      "Experience in fintech or financial services",
      "Strong analytical and strategic thinking skills",
      "Excellent communication and leadership abilities",
    ],
    responsibilities: [
      "Define product vision and roadmap",
      "Gather and prioritize product requirements",
      "Work with engineering and design teams",
      "Analyze market trends and competition",
      "Track product metrics and KPIs",
    ],
    benefits: ["Health Insurance", "Stock Options", "Bonus", "Flexible Hours"],
    skills: ["Product Strategy", "Agile", "Data Analysis", "User Research", "Fintech"],
    postedDate: new Date("2025-01-02"),
    applicants: 1,
    views: 390,
    recruiterId: "rec4",
  },
  {
    id: "5",
    title: "UX/UI Designer",
    company: mockCompanies[4],
    location: "Seattle, WA",
    type: "Full-time",
    experience: "3-5 years",
    salary: "$90k - $130k",
    description:
      "Create beautiful and intuitive user experiences for our healthcare platform. You will work closely with product and engineering teams.",
    requirements: [
      "Bachelor's degree in Design or related field",
      "3+ years of UX/UI design experience",
      "Proficiency in Figma, Sketch, or Adobe XD",
      "Strong portfolio demonstrating design skills",
      "Understanding of user-centered design principles",
    ],
    responsibilities: [
      "Design user interfaces for web and mobile applications",
      "Conduct user research and usability testing",
      "Create wireframes, prototypes, and mockups",
      "Collaborate with developers to implement designs",
      "Maintain design system and style guides",
    ],
    benefits: ["Health Insurance", "Remote Work", "Creative Freedom"],
    skills: ["Figma", "UI Design", "UX Research", "Prototyping", "Design Systems"],
    postedDate: new Date("2025-01-01"),
    applicants: 78,
    views: 520,
    featured: true,
    recruiterId: "rec5",
  },
  {
    id: "6",
    title: "Backend Developer",
    company: mockCompanies[0],
    location: "San Francisco, CA",
    type: "Full-time",
    experience: "3-5 years",
    salary: "$110k - $160k",
    description: "Build robust and scalable backend systems using Node.js and microservices architecture.",
    requirements: [
      "Bachelor's degree in Computer Science",
      "3+ years of backend development experience",
      "Strong knowledge of Node.js and Express",
      "Experience with databases (PostgreSQL, MongoDB)",
      "Understanding of RESTful APIs and GraphQL",
    ],
    responsibilities: [
      "Design and implement backend services",
      "Write efficient database queries",
      "Develop and maintain APIs",
      "Ensure application security and performance",
      "Collaborate with frontend developers",
    ],
    benefits: ["Health Insurance", "401k", "Stock Options", "Gym Membership"],
    skills: ["Node.js", "PostgreSQL", "MongoDB", "GraphQL", "Microservices"],
    postedDate: new Date("2024-12-30"),
    applicants: 42,
    views: 310,
    recruiterId: "rec1",
  },
  {
    id: "7",
    title: "Mobile Developer (React Native)",
    company: mockCompanies[5],
    location: "Remote",
    type: "Remote",
    experience: "2-4 years",
    salary: "$85k - $120k",
    description: "Develop cross-platform mobile applications for our education platform using React Native.",
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      "2+ years of React Native development",
      "Experience with iOS and Android development",
      "Knowledge of mobile app deployment processes",
      "Strong JavaScript/TypeScript skills",
    ],
    responsibilities: [
      "Build and maintain mobile applications",
      "Implement new features and improvements",
      "Optimize app performance",
      "Fix bugs and resolve issues",
      "Collaborate with design and backend teams",
    ],
    benefits: ["Health Insurance", "Remote Work", "Learning Budget", "Flexible Hours"],
    skills: ["React Native", "JavaScript", "TypeScript", "iOS", "Android"],
    postedDate: new Date("2024-12-28"),
    applicants: 56,
    views: 420,
    recruiterId: "rec6",
  },
  {
    id: "9",
    title: "Marketing Manager",
    company: mockCompanies[3],
    location: "Boston, MA",
    type: "Full-time",
    experience: "3-5 years",
    salary: "$80k - $120k",
    description: "Lead marketing campaigns and strategies for our fintech platform.",
    requirements: [
      "Bachelor's degree in Marketing or related field",
      "3+ years of digital marketing experience",
      "Experience with marketing automation tools",
      "Strong analytical and creative skills",
      "Excellent communication abilities",
    ],
    responsibilities: [
      "Develop and execute marketing campaigns",
      "Manage social media presence",
      "Analyze campaign performance",
      "Create marketing content",
      "Collaborate with product and sales teams",
    ],
    benefits: ["Health Insurance", "Bonus", "Flexible Hours"],
    skills: ["Digital Marketing", "SEO", "Content Marketing", "Analytics", "Social Media"],
    postedDate: new Date("2024-12-26"),
    applicants: 33,
    views: 280,
    recruiterId: "rec4",
  },
  {
    id: "10",
    title: "Sales Representative",
    company: mockCompanies[1],
    location: "New York, NY",
    type: "Full-time",
    experience: "2-4 years",
    salary: "$70k - $100k",
    description: "Drive sales growth for our data analytics platform.",
    requirements: [
      "Bachelor's degree in Business or related field",
      "2+ years of sales experience",
      "Strong communication and negotiation skills",
      "Experience with CRM software",
      "Results-oriented mindset",
    ],
    responsibilities: [
      "Identify and qualify leads",
      "Conduct product demonstrations",
      "Close sales deals",
      "Maintain customer relationships",
      "Meet sales targets",
    ],
    benefits: ["Health Insurance", "Commission", "Travel Opportunities"],
    skills: ["Sales", "CRM", "Negotiation", "Lead Generation", "Customer Service"],
    postedDate: new Date("2024-12-25"),
    applicants: 28,
    views: 220,
    recruiterId: "rec2",
  },
  {
    id: "11",
    title: "QA Engineer",
    company: mockCompanies[0],
    location: "San Francisco, CA",
    type: "Full-time",
    experience: "2-4 years",
    salary: "$90k - $130k",
    description: "Ensure quality and reliability of our software products through comprehensive testing.",
    requirements: [
      "Bachelor's degree in Computer Science or related field",
      "2+ years of QA/testing experience",
      "Knowledge of testing methodologies",
      "Experience with automation tools",
      "Attention to detail",
    ],
    responsibilities: [
      "Create and execute test plans",
      "Perform manual and automated testing",
      "Identify and document bugs",
      "Work with developers to resolve issues",
      "Ensure product quality standards",
    ],
    benefits: ["Health Insurance", "401k", "Stock Options"],
    skills: ["QA Testing", "Selenium", "Test Automation", "Bug Tracking", "Agile"],
    postedDate: new Date("2024-12-24"),
    applicants: 19,
    views: 180,
    recruiterId: "rec1",
  },
  {
    id: "12",
    title: "Business Analyst",
    company: mockCompanies[3],
    location: "Boston, MA",
    type: "Full-time",
    experience: "3-5 years",
    salary: "$85k - $125k",
    description: "Analyze business requirements and help drive product development.",
    requirements: [
      "Bachelor's degree in Business or related field",
      "3+ years of business analysis experience",
      "Strong analytical and problem-solving skills",
      "Experience with requirements gathering",
      "Knowledge of agile methodologies",
    ],
    responsibilities: [
      "Gather and document business requirements",
      "Create functional specifications",
      "Work with stakeholders to define needs",
      "Analyze data to identify trends",
      "Support product development process",
    ],
    benefits: ["Health Insurance", "Bonus", "Professional Development"],
    skills: ["Business Analysis", "Requirements Gathering", "Data Analysis", "Agile", "SQL"],
    postedDate: new Date("2024-12-23"),
    applicants: 24,
    views: 210,
    recruiterId: "rec4",
  },
]

export const mockCategories: JobCategory[] = [
  { id: "1", name: "Technology", icon: "Laptop", jobCount: 1250 },
  { id: "2", name: "Design", icon: "Palette", jobCount: 430 },
  { id: "3", name: "Marketing", icon: "TrendingUp", jobCount: 680 },
  { id: "4", name: "Sales", icon: "DollarSign", jobCount: 520 },
  { id: "5", name: "Finance", icon: "PieChart", jobCount: 390 },
  { id: "6", name: "Healthcare", icon: "Heart", jobCount: 780 },
  { id: "7", name: "Education", icon: "GraduationCap", jobCount: 340 },
  { id: "8", name: "Engineering", icon: "Wrench", jobCount: 920 },
]

export const mockUsers: User[] = [
  {
    id: "user1",
    email: "john.doe@example.com",
    name: "John Doe",
    role: "seeker",
    avatar: "/professional-male.jpg",
    phone: "+1 (555) 123-4567",
    location: "San Francisco, CA",
    bio: "Passionate frontend developer with 5 years of experience building modern web applications.",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Node.js"],
    experience: "5 years",
    education: "BS in Computer Science, Stanford University",
    resume: "https://example.com/resumes/john-doe.pdf",
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "user2",
    email: "sarah.smith@example.com",
    name: "Sarah Smith",
    role: "seeker",
    avatar: "/professional-female.png",
    phone: "+1 (555) 234-5678",
    location: "New York, NY",
    bio: "Data scientist with expertise in machine learning and statistical analysis.",
    skills: ["Python", "Machine Learning", "TensorFlow", "SQL", "Data Visualization"],
    experience: "4 years",
    education: "MS in Data Science, MIT",
    resume: "https://example.com/resumes/sarah-smith.pdf",
    createdAt: new Date("2024-02-20"),
  },
  {
    id: "user3",
    email: "mike.johnson@example.com",
    name: "Mike Johnson",
    role: "seeker",
    avatar: "/professional-male.jpg",
    phone: "+1 (555) 345-6789",
    location: "Austin, TX",
    bio: "DevOps engineer specializing in cloud infrastructure and automation.",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "CI/CD"],
    experience: "6 years",
    education: "BS in Computer Engineering, UT Austin",
    resume: "https://example.com/resumes/mike-johnson.pdf",
    createdAt: new Date("2024-03-10"),
  },
  {
    id: "user4",
    email: "emily.chen@example.com",
    name: "Emily Chen",
    role: "seeker",
    avatar: "/professional-female.png",
    phone: "+1 (555) 456-7890",
    location: "Seattle, WA",
    bio: "Full-stack developer with a passion for building scalable applications.",
    skills: ["React", "Node.js", "PostgreSQL", "GraphQL", "AWS"],
    experience: "3 years",
    education: "BS in Software Engineering, University of Washington",
    resume: "https://example.com/resumes/emily-chen.pdf",
    createdAt: new Date("2024-04-05"),
  },
  {
    id: "user5",
    email: "david.brown@example.com",
    name: "David Brown",
    role: "seeker",
    avatar: "/professional-male.jpg",
    phone: "+1 (555) 567-8901",
    location: "Boston, MA",
    bio: "Product manager with technical background and strong leadership skills.",
    skills: ["Product Management", "Agile", "Data Analysis", "User Research", "SQL"],
    experience: "7 years",
    education: "MBA, Harvard Business School",
    resume: "https://example.com/resumes/david-brown.pdf",
    createdAt: new Date("2024-05-15"),
  },
  {
    id: "user6",
    email: "lisa.garcia@example.com",
    name: "Lisa Garcia",
    role: "seeker",
    avatar: "/professional-female.png",
    phone: "+1 (555) 678-9012",
    location: "San Francisco, CA",
    bio: "Frontend developer with design sensibility and attention to detail.",
    skills: ["React", "Vue.js", "CSS", "UI/UX", "Figma"],
    experience: "4 years",
    education: "BS in Computer Science, UC Berkeley",
    resume: "https://example.com/resumes/lisa-garcia.pdf",
    createdAt: new Date("2024-06-01"),
  },
  {
    id: "rec1",
    email: "recruiter@techcorp.com",
    name: "Sarah Johnson",
    role: "recruiter",
    avatar: "/professional-female.png",
    phone: "+1 (555) 987-6543",
    location: "San Francisco, CA",
    companyName: "TechCorp Solutions",
    companyLogo: "/tech-company-logo.jpg",
    createdAt: new Date("2023-06-10"),
  },
  {
    id: "rec2",
    email: "recruiter@dataflow.com",
    name: "Michael Roberts",
    role: "recruiter",
    avatar: "/professional-male.jpg",
    phone: "+1 (555) 876-5432",
    location: "New York, NY",
    companyName: "DataFlow Analytics",
    companyLogo: "/data-analytics-logo.jpg",
    createdAt: new Date("2023-07-20"),
  },
  {
    id: "rec3",
    email: "recruiter@cloudnine.com",
    name: "Jennifer Lee",
    role: "recruiter",
    avatar: "/professional-female.png",
    phone: "+1 (555) 765-4321",
    location: "Austin, TX",
    companyName: "CloudNine Systems",
    companyLogo: "/cloud-systems-logo.jpg",
    createdAt: new Date("2023-08-15"),
  },
]

export const mockApplications: Application[] = [
  {
    id: "app1",
    jobId: "1",
    job: mockJobs[0],
    seekerId: "user1",
    status: "interview_scheduled",
    appliedDate: new Date("2025-01-06"),
    coverLetter: "I am excited to apply for this position as a Senior Frontend Developer. With over 5 years of experience in React and TypeScript, I believe I would be a great fit for your team.",
  },
  {
    id: "app2",
    jobId: "1",
    job: mockJobs[0],
    seekerId: "user2",
    status: "interview_scheduled",
    appliedDate: new Date("2025-01-05"),
    coverLetter: "While my primary expertise is in data science, I have strong frontend development skills and am eager to contribute to your projects.",
  },
  {
    id: "app3",
    jobId: "1",
    job: mockJobs[0],
    seekerId: "user4",
    status: "interview_completed",
    appliedDate: new Date("2025-01-07"),
    coverLetter: "I am a full-stack developer with a passion for creating beautiful and functional user interfaces. I would love to join your team.",
  },
  {
    id: "app4",
    jobId: "1",
    job: mockJobs[0],
    seekerId: "user6",
    status: "pending",
    appliedDate: new Date("2025-01-08"),
    coverLetter: "As a frontend developer with a strong design background, I can bring both technical skills and design sensibility to your team.",
  },
  {
    id: "app5",
    jobId: "2",
    job: mockJobs[1],
    seekerId: "user2",
    status: "accepted",
    appliedDate: new Date("2025-01-04"),
    coverLetter: "With my MS in Data Science from MIT and 4 years of industry experience, I am well-equipped to tackle complex data challenges at your organization.",
  },
  {
    id: "app6",
    jobId: "2",
    job: mockJobs[1],
    seekerId: "user1",
    status: "rejected",
    appliedDate: new Date("2025-01-03"),
  },
  {
    id: "app7",
    jobId: "3",
    job: mockJobs[2],
    seekerId: "user3",
    status: "shortlisted",
    appliedDate: new Date("2025-01-05"),
    coverLetter: "As a DevOps engineer with 6 years of experience in AWS, Docker, and Kubernetes, I am confident I can help optimize your cloud infrastructure.",
  },
  {
    id: "app8",
    jobId: "3",
    job: mockJobs[2],
    seekerId: "user4",
    status: "reviewed",
    appliedDate: new Date("2025-01-06"),
    coverLetter: "My experience with cloud platforms and infrastructure automation makes me a strong candidate for this DevOps role.",
  },
  {
    id: "app9",
    jobId: "4",
    job: mockJobs[3],
    seekerId: "user5",
    status: "shortlisted",
    appliedDate: new Date("2025-01-02"),
    coverLetter: "With an MBA from Harvard and 7 years of product management experience, I am ready to lead product strategy at your fintech company.",
  },
  {
    id: "app11",
    jobId: "9",
    job: mockJobs[7],
    seekerId: "user2",
    status: "pending",
    appliedDate: new Date("2024-12-27"),
    coverLetter: "With my background in data analysis and marketing, I can bring valuable insights to your marketing campaigns.",
  },
  {
    id: "app12",
    jobId: "10",
    job: mockJobs[8],
    seekerId: "user5",
    status: "reviewed",
    appliedDate: new Date("2024-12-26"),
    coverLetter: "My product management experience includes sales strategy and customer relationship management.",
  },
  {
    id: "app13",
    jobId: "11",
    job: mockJobs[9],
    seekerId: "user4",
    status: "shortlisted",
    appliedDate: new Date("2024-12-25"),
    coverLetter: "As a full-stack developer, I have experience with testing and quality assurance practices.",
  },
  {
    id: "app14",
    jobId: "12",
    job: mockJobs[10],
    seekerId: "user5",
    status: "pending",
    appliedDate: new Date("2024-12-24"),
    coverLetter: "My product management background includes extensive business analysis and requirements gathering.",
  },
]

export const mockInterviews: Interview[] = [
  {
    id: "interview1",
    applicationId: "app1",
    application: mockApplications[0],
    interviewerId: "rec1",
    interviewer: mockUsers.find(u => u.id === "rec1")!,
    seekerId: "user1",
    seeker: mockUsers.find(u => u.id === "user1")!,
    type: "online",
    status: "scheduled",
    scheduledDate: new Date("2025-01-15T14:00:00"),
    duration: 60,
    meetingLink: "https://meet.google.com/abc-defg-hij",
    meetingPlatform: "google_meet",
    notes: "Technical interview for frontend developer position",
    createdAt: new Date("2025-01-08T10:00:00"),
    updatedAt: new Date("2025-01-08T10:00:00"),
  },
  {
    id: "interview2",
    applicationId: "app2",
    application: mockApplications[1],
    interviewerId: "rec1",
    interviewer: mockUsers.find(u => u.id === "rec1")!,
    seekerId: "user2",
    seeker: mockUsers.find(u => u.id === "user2")!,
    type: "physical",
    status: "confirmed",
    scheduledDate: new Date("2025-01-12T10:30:00"),
    duration: 90,
    location: "TechCorp Solutions, 123 Innovation Drive, San Francisco, CA 94105",
    notes: "On-site interview with team members",
    createdAt: new Date("2025-01-07T15:30:00"),
    updatedAt: new Date("2025-01-09T09:15:00"),
  },
  {
    id: "interview3",
    applicationId: "app3",
    application: mockApplications[2],
    interviewerId: "rec2",
    interviewer: mockUsers.find(u => u.id === "rec2")!,
    seekerId: "user3",
    seeker: mockUsers.find(u => u.id === "user3")!,
    type: "online",
    status: "completed",
    scheduledDate: new Date("2025-01-05T16:00:00"),
    duration: 45,
    meetingLink: "https://zoom.us/j/123456789",
    meetingPlatform: "zoom",
    notes: "Initial screening interview",
    feedback: "Good technical knowledge, needs more experience with React hooks",
    createdAt: new Date("2025-01-03T11:00:00"),
    updatedAt: new Date("2025-01-05T17:00:00"),
  },
  {
    id: "interview4",
    applicationId: "app4",
    application: mockApplications[3],
    interviewerId: "rec2",
    interviewer: mockUsers.find(u => u.id === "rec2")!,
    seekerId: "user4",
    seeker: mockUsers.find(u => u.id === "user4")!,
    type: "online",
    status: "cancelled",
    scheduledDate: new Date("2025-01-10T13:00:00"),
    duration: 60,
    meetingLink: "https://teams.microsoft.com/l/meetup-join/abc123",
    meetingPlatform: "teams",
    notes: "Technical interview - cancelled due to interviewer availability",
    createdAt: new Date("2025-01-06T14:20:00"),
    updatedAt: new Date("2025-01-09T12:00:00"),
  },
  {
    id: "interview5",
    applicationId: "app5",
    application: mockApplications[4],
    interviewerId: "rec3",
    interviewer: mockUsers.find(u => u.id === "rec3")!,
    seekerId: "user5",
    seeker: mockUsers.find(u => u.id === "user5")!,
    type: "physical",
    status: "scheduled",
    scheduledDate: new Date("2025-01-18T15:00:00"),
    duration: 75,
    location: "DataFlow Analytics, 456 Data Street, New York, NY 10001",
    notes: "Final round interview with CTO",
    createdAt: new Date("2025-01-10T16:45:00"),
    updatedAt: new Date("2025-01-10T16:45:00"),
  },
]

export const mockNotifications: Notification[] = [
  {
    id: "notif1",
    userId: "user1",
    title: "Application Reviewed",
    message: "Your application for Senior Frontend Developer has been reviewed",
    type: "application",
    read: false,
    createdAt: new Date("2025-01-06T10:30:00"),
    link: "/seeker/applications",
  },
  {
    id: "notif2",
    userId: "user1",
    title: "New Job Match",
    message: "5 new jobs match your profile",
    type: "job",
    read: false,
    createdAt: new Date("2025-01-05T14:20:00"),
    link: "/jobs",
  },
  {
    id: "notif3",
    userId: "user1",
    title: "Interview Scheduled",
    message: "You have an interview scheduled for Senior Frontend Developer on January 15, 2025 at 2:00 PM",
    type: "interview",
    read: false,
    createdAt: new Date("2025-01-08T10:00:00"),
    link: "/seeker/interviews",
  },
  {
    id: "notif4",
    userId: "user2",
    title: "Interview Confirmed",
    message: "Your interview for Data Analyst position has been confirmed for January 12, 2025",
    type: "interview",
    read: false,
    createdAt: new Date("2025-01-09T09:15:00"),
    link: "/seeker/interviews",
  },
  {
    id: "notif5",
    userId: "user3",
    title: "Interview Completed",
    message: "Your interview feedback for Product Manager position is now available",
    type: "interview",
    read: false,
    createdAt: new Date("2025-01-05T17:00:00"),
    link: "/seeker/interviews",
  },
]
